# Server Ports
[proxyServiceConfig]
port = 3012
host = "127.0.0.1"

[dataServiceConfig]
port = 3013
host = "127.0.0.1"

[adServerConfig]
port = 3014
host = "127.0.0.1"

[transactionServiceConfig]
port = 3015
host = "127.0.0.1"

[reelsConfig]
port = 3016
host = "127.0.0.1"

[kioskInventoryServiceConfig]
port = 3017
host = "127.0.0.1"

[iotCertificateServiceConfig]
port = 3018
host = "127.0.0.1"

[loyaltyWebConfig] # Web UI is completely optional.
port = 3019
host = "127.0.0.1"
enabled = true

[mqttConfig]
port = 8883
host = "127.0.0.1"

[loyaltyConfig]
# Points per $1.00 spent based on tier (for used disc purchases)
earningMember = 50
earningStar = 50
earningSuperstar = 75
earningLegend = 100

rentalPointsPerNight = 150 # Amount of points earned per night (rentals)
rentalRedemptionGoal = 2000 # Redemption amount needed for 1 free night rental
newPointBalance = 2000 # Signup bonus granted to new members (currently 1 free night)
newTierDefault = "Member" # Default tier the user is signed up for (Member, Star, Superstar, Legend)

# Amount of purchases needed for each tier level-up
tierMemberPurchases = 0 # No minimum requirement
tierStarPurchases = 10 # 10+ purchases minimum
tierSuperstarPurchases = 20 # 20+ purchases minimum
tierLegendPurchases = 50 # 50+ purchases minimum

[dbConfig]
# nothing here yet

# Root Certificate Authority Configuration
[caConfig.rootCaConfig]
common_name = "UnRedbox Root CA 1"
organization = "UnRedbox"
country = "US"
validity_years = 25

# Broker Certificate Configuration (MQTT Broker Cert)
[caConfig.brokerConfig]
# set this to whatever your mqtt broker domain is
# aws used a wildcard `*.iot.unredbox.local` to cover all their customer domains, we dont really need that
common_name = "athena.local" # example for my local network
organizational_unit = "UnRedbox APIs"
organization = "UnRedbox"
locality = "Oakbrook Terrace"
state = "IL"
country = "US"
validity_years = 20
alternative_names = [
    { type = "dns", value = "athena.local" },         # change to match your common name and any alternative names
    { type = "dns", value = "*.iot.unredbox.local" },
    { type = "dns", value = "iot.unredbox.local" },
]
crl_distribution_points = [
    "http://athena.local:3018/api/crl.pem", # only change the domain name and the port (if you change it)
]

# Device Certificate Configuration (Kiosk Certs)
[caConfig.deviceConfig]
common_name = "UnRedbox IoT Certificate"
organizational_unit = "UnRedbox APIs"
organization = "UnRedbox"
locality = "Oakbrook Terrace"
state = "IL"
country = "US"
validity_years = 20

# Certificate Revocation List Configuration
[caConfig.crlConfig]
validity_years = 1

# Redbox Desktop + Field Maintenance Credentials
[[loginInfo.desktop]] # Redbox Desktop
username = "admin"
password = "1234"

[[loginInfo.field]] # Field Maintenance
username = "admin"
password = "1234"

# ... add any more logins here
