/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IOTCertificateValidRequest {
  certificateId: string;
  name: string;
  thingGroupName: string;
  type: string;
}
