/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AuthorizeRequest {
  AuthAcceptFlag?: boolean;
  AuthAmount?: number;
  AuthRuleId?: number;
  CreditCard: CreditCard;
  CustomerProfileNumber: string;
  ShoppingCart: ShoppingCart;
  SkipAuthRule?: boolean;
  TransactionDate: Date;
}

export interface BlurayUpsell {
  Offer: string;
  ProductGroupId: number;
  TitleId: number;
  TypeId?: number;
}

export interface CreditCard {
  BIN: string;
  CardId: string;
  CardSourceType?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  CardType: number;
  ContactlessEnabled: boolean;
  EmvEnabledTerminal: boolean;
  ExpirationMonth: string;
  ExpirationYear: string;
  FallbackType?: number;
  FirstName: string;
  ICEncryptedData: string;
  IsEncrypted: boolean;
  KSN: string;
  KeyId?: number;
  LastFour: string;
  LastName: string;
  Number: string;
  PostalCode: string;
  ReaderSerialNumber: string;
  Track2: string;
}

export interface Discount {
  Amount: number;
  ApplyOnlyToProduct?: boolean;
  DiscountType: number;
  ProductId: number;
  PromotionCode: string;
  PromotionCodeValue?: string;
  PromotionIntentCode?: string;
  RedemptionPoints?: number;
  Status: number;
}

export interface LineItem {
  Barcode: string;
  BlurayUpsell: BlurayUpsell;
  OfferCode: string;
  Pricing: Pricing;
  ProductFamily: string;
  ProductId: number;
  ProductName: string;
  ProductType: string;
  SourceType?: number;
  SubscriptionId: string;
  TempPassword: string;
  TivoQueryId: string;
  VendStatus: number;
}

export interface LineItemGroup {
  GroupType: number;
  Items?: LineItem[];
  Totals: Totals;
}

export interface Pricing {
  DefaultExtraNight?: number;
  DefaultInitialNight?: number;
  Expiration: number;
  ExtraNight: number;
  InitialDays?: number;
  InitialNight: number;
  NonReturn: number;
  NonReturnDays: number;
  PriceSetId: number;
  ProductPriceId?: number;
  Purchase: number;
}

export interface ShoppingCart {
  Discounts?: Discount[];
  Groups?: LineItemGroup[];
}

export interface Totals {
  DiscountedSubtotal: number;
  GrandTotal: number;
  Subtotal: number;
  TaxAmount: number;
  TaxRate: number;
}
