/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ReturnRequest {
  Barcode: string;
  Deck: number;
  FailedSecurityRead: boolean;
  KioskId: number;
  MessageId: string;
  ReturnDate: Date;
  ReturnType: number;
  Slot: number;
}
