/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface KioskAuthenticateRequest {
  Password: string;
  UseNtAuthentication: boolean;
  Username: string;
  /**
   * Unknown Property
   */
  [x: string]: unknown;
}

export interface KioskCampaignsRequest {
  LastSyncTime?: Date;
}

export interface PromoCodeValidationRequest {
  Code: string;
  KioskId: number;
  MessageId: string;
}
