/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface KioskAuthenticateRequest {
  Password: string;
  UseNtAuthentication: boolean;
  Username: string;
  /**
   * Unknown Property
   */
  [x: string]: unknown;
}
