/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface PromoCodeValidationRequest {
  Code: string;
  KioskId: number;
  MessageId: string;
}
