/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AuditEventRequest {
  CreatedOnLocal?: string;
  EventType?: string;
  KioskId?: number;
  LogDate?: string;
  Message?: string;
  MessageId?: string;
  SendToTable?: boolean;
  Source?: string;
  Username?: string;
}
