/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface KioskVersionRequest {
  CreatedOn?: string;
  CreatedOnLocal?: string;
  KioskId?: number;
  MessageId?: string;
  SendToTable?: boolean;
  UniqueId?: string;
  Versions?: {
    [pattern: string]: string;
  };
}
