/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface KioskEventsRequest {
  CreatedOn?: string;
  CreatedOnLocal?: string;
  KioskEventsData?: string;
  KioskId?: number;
  MessageId?: string;
  SendToTable?: boolean;
}
