/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface KioskAlertRequest {
  AlertMessage: string;
  AlertType: number;
  CreatedOn: Date;
  CreatedOnLocal: Date;
  KioskId: number;
  MessageId: string;
  SendToTable?: boolean;
  SubAlertType: string;
  UniqueId: string;
}
