/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface KioskFunctionCheckRequest {
  CameraDriver?: string;
  CreatedOn?: string;
  CreatedOnLocal?: string;
  InitTest?: string;
  KioskId?: number;
  MessageId?: string;
  ReportTime?: string;
  SendToTable?: boolean;
  SnapDecode?: string;
  TouchScreenDriver?: string;
  TrackTest?: string;
  UserName?: string;
  VendDoor?: string;
  VerticalSlot?: string;
}
