/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface KioskPropertiesRequest {
  CreatedOn?: string;
  CreatedOnLocal?: string;
  KioskId?: number;
  MessageId?: string;
  Properties?: {
    [pattern: string]: string;
  };
  SendToTable?: boolean;
}
