/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface KioskStatistics {
  Damaged?: string;
  DumpBin?: string;
  EmptySlots?: string;
  InventoryData?: string;
  ProfileData?: string;
  RebalancesInKiosk?: string;
  ThinDiscs?: string;
  TotalDiscs?: string;
  UnknownDiscs?: string;
  UnknownTitle?: string;
  UnmatchedInKiosk?: string;
  WrongTitle?: string;
}

export interface KioskStatisticsRequest {
  CreatedOn?: string;
  CreatedOnLocal?: string;
  KioskId?: number;
  MessageId?: string;
  SendToTable?: boolean;
  Statistics?: KioskStatistics;
}
