/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface RebootStatusRequest {
  ConnectTime?: string;
  DeviceTime?: string;
  DisconnectTime?: string;
  ExpectedTime?: string;
  Id?: string;
  KioskId?: number;
  Type?: 'Scheduled' | 'Manual' | 'Automatic' | 'Disconnect' | 'FileUpdate' | 'OfflineCommandFailure' | 0 | 1 | 2 | 3 | 4 | 5;
}
