/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface RebootStatusRequest {
  ConnectTime?: Date;
  DeviceTime?: Date;
  DisconnectTime?: Date;
  ExpectedTime?: Date;
  Id?: string;
  KioskId: number;
  Type:
    | "Scheduled"
    | "Manual"
    | "Automatic"
    | "Disconnect"
    | "FileUpdate"
    | "OfflineCommandFailure"
    | 0
    | 1
    | 2
    | 3
    | 4
    | 5;
}
