/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface MerchandingStatusUpdateSchema {
  Barcode: string;
  MerchandStatus?: string;
  MessageId?: string;
  ThinDateUTC?: string;
  ThinReasonCode?: string;
  UpdateDateTimeUTC: Date;
}

export type UpdateMerchandizingStatusRequest = {
  Barcode: string;
  MerchandStatus?: string;
  MessageId?: string;
  ThinDateUTC?: string;
  ThinReasonCode?: string;
  UpdateDateTimeUTC: Date;
}[];
